import AppwriteIcon from "../static/appwrite-icon.svg";

export const metadata = {
  title: "Appwrite starter",
  description: "Generated by Appwrite cloud",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={AppwriteIcon} />
      </head>
      <body>{children}</body>
    </html>
  );
}
